services:
  db:
    image: postgres:17.4-alpine3.21
    container_name: db
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build:
      dockerfile: api.Dockerfile
    container_name: api
    environment:
      OIDC_DEMO_ENV: ${OIDC_DEMO_ENV}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-demo}
      POSTGRES_DB: demo
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      - db

volumes:
  db_data: