// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DemoUser struct {
	ID        pgtype.UUID
	Username  string
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
