// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dal

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DemoIdentity struct {
	ID                 pgtype.UUID
	IdentityProviderID string
	UserID             pgtype.UUID
	ExternalID         string
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

type DemoIdentityProvider struct {
	ID        string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type DemoStateToken struct {
	Token     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type DemoUser struct {
	ID        pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
