// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package dal

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUser = `-- name: GetUser :one
select id, username, email, created_at, updated_at
from demo."user"
where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (DemoUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i DemoUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
